### ISSUE TITLE
Some emoji icon not show in HTC One-M8

### ISSUE THREAD

**Issue by nguyenvp08** [googlesamples/android-EmojiCompat#12]
I replaced the text with code U+1F396 (🎖) by code [new String(Character.toChars(0x1f396))].
But the icon not show in the device HTC One M8 (show an invalid icon), I used the downloadable font and see the log the initialization is successful. 
There are a lot of icons not shown too.

**Comment by siyamed** [comment]
Currently emojicompat does not render symbols as emojis. 1F396 does not have default Emoji_Presentation, and in order to display it needs emoji variation selector (FE0F).

We might include symbols as emoji in future.

**Comment by nguyenvp08** [comment]
Thank @siyamed , I added the Emoji Variation Selector and display most of the icons but symbols, Hope the emoji appcompat can add these icons soon, thanks
