### ISSUE TITLE
Emoji as unicode 

### ISSUE THREAD

**Issue by ritesh94** [googlesamples/android-EmojiCompat#16]
How do I get Emojis displayed/entered in TextView/EditText as unicode for sending it to server?

**Expected Output**
User enter this emoji: 👩‍
When editText.getText().toString() is performed, it shoud result into: `\uD83D\uDC69`

**Comment by siyamed** [comment]
This has nothing to do with emojicompat.

**Comment by ritesh94** [comment]
Got it.

To display: EmojiTextView can render 👩‍ by passing \uD83D\uDC69

To get the Emoji from EditText or TextView as \uD83D\uDC69 for sending to server, I am using **StringEscapeUtils**.

`StringEscapeUtils.escapeJava(textView.getText().toString())` // 👩‍
outputs `\uD83D\uDC69`
